services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - POSTGRES_URL=postgres://gourmet_user:gourmet_pass@db:5432/gourmet_db
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=gourmet_db
      - POSTGRES_USER=gourmet_user
      - POSTGRES_PASSWORD=gourmet_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
